services:
  db:
    image: postgres:18 # 18 версия указана в тестах (tests\conftest.py)
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes: [db-data:/var/lib/postgresql]
    networks: [main]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 2s
    ports: [5432:5432]
    env_file: [.env]


# TODO: подумать, что с этим делать.
# Старый TODO: Убрать это всё, так как бекенд должен быть развёрнут именно на хост машине
# для работы, через докер ТОЛЬКО вспомогательные сервисы (БД, Redis, Celery и т.д
# Потому-что не получится: 1 - дебажить, 2 - генерировать миграции и мб что-то ещё
#                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
# UPD: Можно делать без поднятия сервера, нужна только БД (можно открыть для хоста)
# (не убрать, а перенести в .prod, убрать только watch и tty)

  # backend:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #   ports: [8000:8000]
  #   command: >
  #     sh -c "
  #       uv run alembic upgrade head &&
  #       exec uv run fastapi dev
  #         --host 0.0.0.0
  #         --port 8000
  #         --reload
  #     "
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "127.0.0.1:8000/api/healthcheck"]
  #     interval: 1m30s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 5s
  #   develop: # file syncing
  #     watch:
  #       - path: ./
  #         action: sync
  #         target: /app
  #         ignore:
  #           - uv.lock
  #       - path: ./uv.lock
  #         action: rebuild
  #       - path: ./alembic/
  #         action:
  #   networks: [main]
  #   env_file: [.env]
  #   tty: true # needs for colored output in attached console, disable ansi-codes removing

volumes:
  db-data:

networks:
  main:
    driver: bridge
