"""change User email & full_name lengths

Revision ID: 80bbb1a1ceb3
Revises: f3b751e07090
Create Date: 2026-07-01 17:02:42.499532

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bbb1a1ceb3'
down_revision: str | Sequence[str] | None = 'f3b751e07090'
branch_labels: str | Sequence[str] | None = None
depends_on:    str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=128),
                    existing_nullable=False)
    op.alter_column('users', 'full_name',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=150),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
