"""add is_active to User

Revision ID: f3b751e07090
Revises: d4f51f3bcf60
Create Date: 2026-07-01 12:45:56.808952

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b751e07090'
down_revision: str | Sequence[str] | None = 'd4f51f3bcf60'
branch_labels: str | Sequence[str] | None = None
depends_on:    str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
